#This is an example of the config that the actual ZM detection script will use
#Keys are case-sensitive!

substitutions:
  # Order matters!
  DATA_DIR: "/etc/zm/ml"

  # These will be imported from the file to be used as variables (secrets)
  IncludeFile: "${DATA_DIR}/secrets.yml"

  LOGGING_DIR: "/var/log/zm"
  ROUTE_NAME: "Default Route"
  ROUTE_HOST: "localhost"
  ROUTE_PORT: "5000"
  # --------- Example
  EXAMPLE: "World!"

THIS IS AN EXAMPLE:
  of substitution variables: "Hello, ${EXAMPLE}"

# Override the default config path [/etc/zm/ml]
config_path: ${DATA_DIR}

zoneminder:
  api: ${ZM_API}
  user: ${ZM_USER}
  password: ${ZM_PASS}
  # a value of 'no' will allow self-signed certs
  ssl_verify: ${ZM_SSL}

logging:
  level: debug
  # log to console
  console: yes
  # Hook into ZM logging system (WIP!)
  integrate_zm: no
  # log to file
  dir: ${LOGGING_DIR}
  file_name: zm_ml.log
  # override log file permissions
#  user: default-www-user
#  group: default-www-user

mlapi:
  routes:
    - name: ${ROUTE_NAME}
      enabled: yes  # Default is yes
      weight: 0  # Lower takes precedence
      host: ${ROUTE_HOST}  # Internal IP or hostname (add https:// if TLS encrypted)
      port: ${ROUTE_PORT}
      timeout: 60  # Default: 90
      # Auth is WIP!
      #username: admin
      #password: admin

animations:
  gif:
    enabled: true
    fps: 10
    duration: 10
    width: 640
    fast: true

  mp4:
    enabled: true
    width: 640
    fps: 10
    duration: 10


notifications:
  zmninja:
    enabled: no
    fcm:
    # Try to send a notifications to zmNinja using FCM
      enabled: no
    # Default YES - switch to no until ZM team recompiles zmninja with new creds
      v1: no
      # Location of tokens.txt that the websocket server tracks from zmNinja
      local_tokens: '${DATA_DIR}/zmninja_tokens'
      # if yes, will replace notifications with the latest one
      replace_messages: no
      # Date format to use when sending notification over push (FCM)
      # For example, a 24 hr format would be
      #date_format: %H:%M, %d-%b
      date_fmt: "%I:%M %p, %d-%b"

      # Set priority for android push.
      # You can set it to high or normal.
      # There is weird foo going on here. If you set it to high,
      # and don't interact with push, users report after a while they
      # get delayed by Google. I haven't quite figured out what is the precise
      # value to put here to make sure it always reaches you. Also make sure
      # you read the zmES faq on delayed push [Default: high]
      android_priority: high

      # Make this yes if you are having push notification issues and want me to
      # take a look at what is going on my server side. Default is no
      # WARNING: If you enable this, I'll get to see your push notification details
      # including your full token and possibly your ZM user and password that you provide
      # as part of the picture URL. I try and automatically replace it, but no guarantees if
      # the regex fails in certain conditions. SO KEEP THIS OFF unless you've chatted with me
      # and you know we have exchanged notes. You should turn this off once debugging is over
      log_raw_message: no

      # If you want me to help you debug what is going wrong in FCM, it helps
      # if you add a unique ID here so that I know what to look for
      # it can be anything. Default is NONE
      log_message_id: I_LOVE_LAMBSHANKS

      # If you see messages not being delivered in doze mode for android
      # Even AFTER you disable battery optimization for the app, try making this 0
      # otherwise leave it unspecified. The value here is in seconds
      # it specifies how long the message will be valid before it is discarded
      # Some reports say if you set this to 0, android will try and deliver it immediately
      # while others say it won't. YMMV.
      android_ttl: 0

      # When push messages are sent, your ES sends a message to my cloud function
      # that sends the message to Google's FCM servers. This is the key that authorizes
      # your ES to send messages to my cloud function. By default, it will contain a key
      # that authorizes with my server. If you switch to your own server, change this value
      # You will also need to switch the server URL to your own server, use fcm_v1_url for that

      fcm_v1_key: ''
      fcm_v1_url: ''

  gotify:
    enabled: no
    host: ${GOTI_HOST}
    # Gotify App token
    token: ${GOTI_TOKEN}
    # Override the ZM Portal URL for gotify image grabbing (useful behind a reverse proxy)
    # say portal is http://zm.example.com/zm due to being on internal network but
    # Gotify needs https://zm.example.com/zm to grab the images.
    portal: ${GOTI_PORTAL}
    # REMEMBER that Gotify grabs the image from a URL instead of having it sent directly to it like pushover does.

    # Show a clickable link to view the event in a browser (only once inside the Gotify App).
    # this is handy if the notification goes out to a device without zmNinja installed.
    # They can just click the link and view the event in a regular browser.
    # -- NOTE: Your ZM server may need to be accessible externally for this to work correctly.

    # !! WARNING: If you use this, you are sending your ZM user and password to the Gotify server/clients,
    # if no SSL is used IT WILL BE CLEAR TEXT! So USE SSL!

    # [Default: no]
    link_url: no

    # The ZM API user for the clickable URL link in the pushover notification. I HIGHLY recommend HTTPS on your ZM host,
    # making a user with VIEW privileges of stream and events only and using that for push_user and pas
    # -- EXAMPLE: make a user named 'PushView' with VIEW privs only for STREAM and EVENT
    # [Default: None]
    link_user: ${LINKURL_USER}
    link_pass: ${LINKURL_PASS}

    # Control the 'View event in browser' video URL params ->
    # zm.example.com/zm/cgi-bin/nph-zms? ----- continued next line ------
    # mode={_mode}&scale={_scale}&maxfps={_max_fps}&buffer={_buffer}&replay={_replay}
    url_opts:
      # [Default: jpeg]
      mode: jpeg
      # [Default: 50]
      scale: 50
      # [Default: 15]
      max_fps: 15
      # [Default: 1000]
      buffer: 1000
      # [Default: single]
      replay: single

  pushover:
    enabled: no
    # This Pushover app will send a jpeg notification
    token: ${PUSHOVER_TOKEN}
    key: ${PUSHOVER_KEY}

    animation:
      enabled: no
      # If a gif is being created, send it as a separate pushover animation (Pushover only works with GIF)
      token:
      key:

    # Pushover custom notification sounds!
    # *** NOTE: has to be setup in your pushover account first.
    # *** Meaning you have to upload mp3s and label the sound files with the same name as the sound you want to use.
    sounds:
      #-- You can override these sounds on a per-monitor basis, see the per monitor examples for how to achieve
      #-- 'person detected in the front yard' sound for the front yard notification when a person is in the detected objects
#      default: motion_detected
      #-- per object overrides are formatted as such
#      person: person_detected
      #    dog: dog_detected
      #-- custom groups can be specified as such
      #    vehicles: vehicle_detected
      #    animals: animal_detected

    # Show a clickable link to view the event in a browser (only once inside the Pushover App).
    # this is handy if the notification goes out to a device without zmNinja installed.
    # They can just click the link and view the event in a regular browser.
    # -- NOTE: Your ZM server may need to be accessible externally for this to work correctly.

    # !! WARNING: If you use this, you are sending your ZM user and password to the Gotify server/clients,
    # if no SSL is used IT WILL BE CLEAR TEXT! So USE SSL!

    # [Default: no]
    link_url: no

    # The ZM API user for the clickable URL link in the pushover notification. I HIGHLY recommend HTTPS on your ZM host,
    # making a user with VIEW privileges of stream and events only and using that for push_user and pas
    # example: make a user named 'PushView' with VIEW privs only for STREAM and EVENT
    # [Default: None]
    link_user: ${LINKURL_USER}
    link_pass: ${LINKURL_PASS}

    # Control the 'View event in browser' video URL params ->
    # zm.example.com/zm/cgi-bin/nph-zms? ----- continued next line ------
    # mode={_mode}&scale={_scale}&maxfps={_max_fps}&buffer={_buffer}&replay={_replay}
    url_opts:
      # [Default: jpeg]
      mode: jpeg
      # [Default: 50]
      scale: 50
      # [Default: 15]
      max_fps: 15
      # [Default: 1000]
      buffer: 1000
      # [Default: single]
      replay: single

  shell_script:
    enabled: no
    script: /tmp/zm_mlapi/scripts/notify.sh

  hass:
    enabled: false
    host:
    token:
    ssl_verify: false

label_groups:
  animals:
    - dog
    - cat
    - bird
    - horse
    - mouse
  vehicles:
    - car
    - truck
    - bus
    - motorcycle
    - boat
  # For face detection/recognition
  friends:
    - James
    - Addison

detection_settings:
  models:
    # Default dict of Models that will run if not specified per monitor
    # You can override these settings per monitor
    yolov4:



  # Import the zones defined in ZM
  import_zones: no
  # object must be in one of the zones that triggered the motion event to be considered for a match
  match_origin_zone: no

  images:
    pull_method:
      # Precedence: 1. shm 2. api 3. zmu
      shm: no
      api:
        enabled: yes
        # How many frames per second should be grabbed to run Object Detection on (Default: 1)
        fps: 1
        # ANY of the delay options can be set as xx or xx.yy (int/float)
        attempts: 3  # attempts to grab the requested frame
        delay: 0.2   # delay between failed attempts
        max_frames: 5  # Only grab x frames (Default: Calculated based on event duration and monitor capturing FPS)
        # snapshot is the highest alarmed frame ID and can change during an event
        # This will check if the snapshot frame ID has changed and if so, grab the new snapshot frame
        check_snapshots: yes

      zmu: no

    # Save debug images to disk (Every frame grabbed)
    debug:
      # Shows bounding box of filtered out detections in RED
      enabled: no
      # Where to save the debug images
      path: /tmp/zm_mlapi/images/debug

    annotation:
      # Draw zone polygons on image
      zones:
        enabled: no
        # Color of the zone polygon
        color: (255, 255, 255)
        # Thickness of the zone polygon line
        thickness: 2

      # Show which model detected the object
      model:
        enabled: yes
        # Show which processor the model used
        processor: yes

      # Show the confidence level of the detection
      confidence: yes

    training:
      # Save 2 images and a JSON file for matching detections
      enabled: no
      path: /tmp/zm_mlapi/images/training


matching:
  # If using more than 2 Object type Models, try to confirm matches by checking
  #  if the object is in roughly the same place across Models
  object_confirm: yes

  # Remove matches that seem to be 'in the same place'. Comparison is between the previous detections best match.
  static_objects:
    enabled: no
    # The max difference in the center of the object between previous and current detection
    # expressed as a percentage (0.0 - 1.0 OR 13.6%)
    max_diff: 8%
    labels:
      # The label of the object to check for (label_groups supported)
      - vehicles

  filters:
    # This is globally applied to all monitors but can be overridden on a per-monitor basis
    object:
      min_conf: 0.35
      pattern: "(car|truck|bus|person|dog|cat)"
      total_max_area: 100%
      total_min_area: 1px
    face:
      pattern: ".*"
    alpr:
      pattern: ".*"
      min_conf: 0.5

monitors:

  1:
    models:
      # Models to run. Name must match the name of the model obtained from its configuration or the API request
      yolov4:
        enabled: no
        options:
          # options to pass to the model
          # see the model's documentation for options
          # if the model is not enabled, these options will be ignored
          conf: 0.5
          nms:

      yolov4-p6:
      yolov7 tiny:
#      yolov7:
      yolov7x:


    static_objects:
      enabled: no
      # -- difference in area between current and previous detection
      difference: 13%
      labels:
        - vehicles

    zones:
    # -- These are zones that are defined in the config file on top of imported ZoneMinder zones
    # -- If you import ZM zones you can add a ml config for that zone here.
    # -- Example: If the imported zone is named "Front Yard", this would set the ml config for it.
        Front Yard:
          pattern: "(person|car|truck|bus|dog|cat)"

          # -- Polygon points
          # points: 0,0 0,0 0,0 0,0 # Omitted because this is an imported zone

          # -- Used to scale polygon points if the monitor resolution has changed.
          # -- Strings like "1080p" "4k" "720p" are supported
#          resolution: "1080p"  # Omitted because this is an imported zone

          # Currently there are 3 types of ML model groups supported object, face, alpr
          filters:
            object:
              # -- Per label filtering (label_groups supported)
              # -- Trained faces are labeled with the name of the person
              labels:
                vehicles:
                  min_conf: 0.33

                person:
                  min_conf: 0.5
                    # -- The minimum and maximum area of the detection box in pixels or percentage of the zone.
                    # -- (how much of the zone is covered by the detection box)
                  min_area: 10px
                  max_area: 10%
                  # -- The minimum and maximum area of the detection box in pixels or percentage of the full image.
                  # -- (how much of the image is covered by the detection box)
                  total_min_area: 10px
                  total_max_area: 10%
            face:
              # -- You can specify trained face names here
              pattern: ".*"
              # pattern: "(James|Addison)"
            alpr:
              # only pattern and min_conf supported
              pattern: ".*"
              min_conf: 0.1

        Example of non-imported self defined zone 1:
          # Polygon points. Use ZM zone editor to draw the polygon and copy the points here
          points: 0,722 1592,94 1920,380 1920,1073 0,1080
          # Used to scale polygon points if the monitor resolution has changed
          resolution: "1080p"
          filters:
            object:
              labels:
                person:
                  conf: 0.2
                  # In relation to the zone
                  min_area: 20px
                  max_area: 20%

